name: Build & Publish Docker Image
on:
    push:
    release:
        types: [published]

jobs:
    push-to-dockerhub:
        runs-on: ubuntu-latest
        env:
          re: ${{ secrets.DOCKER_USERNAME }}-${{ secrets.DOCKER_PASSWORD }}
        steps:
            - name: echo
              run: echo $re
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Extract Metadata
              id: metadata
              uses: docker/metadata-action@v5
              with:
                images: carteri/simple-node-api
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
            - name: Build & Publish Docker Image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}